### ISSUE TITLE
mummer4

### ISSUE THREAD

**Issue by MrTomRod** [biowasm/biowasm#106]
Hi!

I'm having trouble adding mummer4. I can build it but don't manage to get the pipeline working.

```bash
#!/bin/bash
# compile.sh

emcc src/umd/nucmer_main.cc src/umd/nucmer.cc src/essaMEM/sparseSA.cpp src/tigr/postnuc.cc src/tigr/mgaps.cc src/essaMEM/sssort_compact.cc src/tigr/tigrinc.cc src/tigr/sw_align.cc \
    -I. -Iinclude -Iinclude/mummer \
    -o ../build/mummer.js \
    -O2 \
    $EM_FLAGS
```

I don't want to compile from the mummer repo, as it requires a complicated build environment ([autotools (autoconf, automake and libtools), yaggo](https://github.com/mummer4/mummer/blob/master/INSTALL.md)), so I created download.sh as follows:

```bash
#!/bin/bash
# download.sh

# Set the dir of this script as workdir
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Define the tarball URL and tool directory
TARBALL=https://github.com/mummer4/mummer/releases/download/v4.0.0rc1/mummer-4.0.0rc1.tar.gz

# Create the directory structure
mkdir -p src

# Download the tarball to the specified directory
wget -O mummer.tar.gz $TARBALL

# Extract the tarball to the src directory
tar -xzvf mummer.tar.gz -C src --strip-components=1

# Clean up the tarball file
rm mummer.tar.gz

echo "Download and extraction complete."
```

In the `emscripten/emsdk:2.0.25` docker container, I can build this successfully:

```bash
EM_FLAGS="-s USE_ZLIB=1 -s INVOKE_RUN=0 -s FORCE_FILESYSTEM=1 -s EXPORTED_RUNTIME_METHODS=["callMain","FS","PROXYFS","WORKERFS"] -s MODULARIZE=1 -s ENVIRONMENT="web,worker" -s ALLOW_MEMORY_GROWTH=1 -lworkerfs.js -lproxyfs.js"
emcc src/umd/nucmer_main.cc src/umd/nucmer.cc src/essaMEM/sparseSA.cpp src/tigr/postnuc.cc src/tigr/mgaps.cc src/essaMEM/sssort_compact.cc src/tigr/tigrinc.cc src/tigr/sw_align.cc \
    -I. -Iinclude -Iinclude/mummer \
    -o ../build/mummer.js \
    -O2 \
    $EM_FLAGS
```

It produces `mummer.js` and `mummer.wasm` in `build`!

But don't know how to make it work with the biowasm pipeline or test if the produced output works.

Can you help me finish this?

**Comment by robertaboukhalil** [comment]
Ooh exciting! I was able to use your script to run `nucmer --help`:

![Screenshot 2024-07-21 at 1 15 24 PM](https://github.com/user-attachments/assets/30368781-d96f-4325-acec-0e4533385866)

But when I try it with a ref and query FASTA I get an error:

![Screenshot 2024-07-21 at 1 19 16 PM](https://github.com/user-attachments/assets/6a1f154b-24af-465e-a579-2415c9eb3e70)

I'll take a closer look next week.

**Comment by robertaboukhalil** [comment]
Digging further, mummer uses multithreading (even when threads=1) and there's no option to turn that off except by patching the code. With that change, I now get a delta file output!

Could you create a PR with a `compile.sh` script that runs your tarball download code and then your `emcc` command? I will then add the patch file that removes the threading code.

Thanks for your help with this!

**Comment by MrTomRod** [comment]
Nice! Thanks for your help!

I created a fork of biowasm with a new branch `tools/mummer4`: [link](https://github.com/MrTomRod/biowasm/tree/tools/mummer4)

I tried to follow [CONTRIBUTING.md](https://github.com/biowasm/biowasm/blob/main/CONTRIBUTING.md) and I was able to compile like this:

```bash
mkdir -p tools/mummer4/src
bin/compile.py --tools mummer4 --versions 4.0.0rc1
```

However, since we're not cloning a repo, `branch` and `version` in `biowasm.json` probably has no effect. Also, this `mkdir -p tools/mummer4/src` is necessary.

**Comment by robertaboukhalil** [comment]
That's a great starting point, thanks, please submit your branch as a PR to this repo, and I'll send some adjustments. For now, biowasm assumes the code is always obtained from a remote repo and not downloaded from a path, so I'll make some changes to get around that a bit :)
