### ISSUE TITLE
Using CLI gzip in biowasm?

### ISSUE THREAD

**Issue by niemasd** [biowasm/biowasm#109]
Hey! I'm working on a project where we may want to gzip some files client-side. I originally tried [fflate](https://101arrowz.github.io/fflate/), but it was *way* slower (and resulted in a larger compressed file) than just running command line `gzip` in the sandbox.bio playground. Because of this, I was hoping to use command line `gzip` within Aioli. However, `gzip` doesn't seem to be part of `coreutils` in biowasm:

https://biowasm.com/cdn/v3/coreutils/8.32

Is there any way for me to use CLI `gzip` in my own web app through Aioli in a manner similar to how I used it in the sandbox.bio playground?

**Comment by robertaboukhalil** [comment]
Gzip isn't available on biowasm but bgzip is, would that work for you? sandbox.bio v2 doesn't use biowasm, so the tools available are different.

Otherwise there's also the JS library pako or the JS API CompressionStream.

**Comment by niemasd** [comment]
Ah, I see; thanks for clarifying! Thanks for the pointers! I'll check those options out!

**Comment by niemasd** [comment]
Just benchmarked pako, and it was like 30-60x faster than fflate (it was on-par with sandbox.bio gzip), so I'll probably just use pako! Thanks for the tip!!

**Comment by robertaboukhalil** [comment]
Awesome, thanks for the data point!
