### ISSUE TITLE
streaming output data

### ISSUE THREAD

**Issue by dridk** [biowasm/biowasm#114]
Is it possible to generate data outfitting the memory?

For instance : 

`samtools sort > data.sam 
`

Actually, it looks like we can only get the command data output in the memory. Is there a way to create file and fill data in it ? 
I don't think so, but I Ask

**Comment by robertaboukhalil** [comment]
Not directly with biowasm, but for the example you gave, you can do something like `samtools sort -o data.sam` so it's saved to the file directly

**Comment by dridk** [comment]
you mean in the virtual file system ?

**Comment by robertaboukhalil** [comment]
Yes, correct, so in this case you could do:

```
[...]
await CLI.exec("samtools sort -o data.sam ...")
await CLI.download("data.sam")
[...]
```

and you can download data.sam without having to handle stdout yourself

This isn't a general solution since some tools don't have a `-o` parameter but it works for many tools
