### ISSUE TITLE
"samtools index" did not work

### ISSUE THREAD

**Issue by pinbo** [biowasm/biowasm#27]
Hello, I tried the samtools playground, but seems `samtools index` did not work. Here is the message:

_samtools index: failed to create or write index_

Thanks.

**Comment by robertaboukhalil** [comment]
Hi @pinbo, curious what's the full command you entered? And were you using the `A549.bam` demo file or did you specify a custom local file? Thanks!

**Comment by pinbo** [comment]
I uploaded my own data (2.sorted.bam) and run `samtools index /data/2.sorted.bam`

I think I figured out: folder **/data** is not writable. I need to direct the output to the folder "/samtools/examples".

Thanks.
