### ISSUE TITLE
samtools sort not working

### ISSUE THREAD

**Issue by pinbo** [biowasm/biowasm#28]
Hi There,

I just found a new issue: `samtools sort` output is not sorted. Seems it did not do anything. The content is still the same as the unsorted bam or sam files. Here is how I tested it:

1. Upload a sam file 2.sam;
2. samtools sort /data/2.sam -o /samtools/examples/2.bam
3. samtools index  /samtools/examples/2.bam

Then I got the error:
`[E::hts_idx_push] NO_COOR reads not in a single block at the end 1 -1
[E::sam_index] Read 'M02034:479:000000000-D7LT7:1:1101:13367:1705' with ref_name='DELLA-4B-Kronos', ref_length=301, flags=73, pos=62 cannot be indexed
samtools index: failed to create index for "/samtools/examples/2.bam": No such file or directory`

Then I checked the contents of the 2.bam with `samtools view  /samtools/examples/2.bam` and the reads order are the same as the sam file.

Thanks!

**Comment by robertaboukhalil** [comment]
Thanks for catching that! I'll take a closer look.

---

**Notes to self**

Can reproduce the issue with this `test2.sam` file:

```
@HD	VN:1.6	SO:coordinate
@SQ	SN:CHROMOSOME_I	LN:1009800	M5:8ede36131e0dbf3417807e48f77f3ebd
@PG	ID:bowtie2	PN:bowtie2	VN:2.0.0-beta5
SRR065390.15493040	0	CHROMOSOME_I	999912	42	100M	*	0	0	ACTTCAAGCAGAGGATTTTTCGATGATTGCCAAAAATTTTGGAACTTTTATAGGCTTAAGCTTATGGTTATGTTTAGGCGTAGGCTTAGGCTTAGGCGTA	CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDBCCBDBCCBDDA@>DC?5@?@@??:><<>8>39<37	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:100	YT:Z:UU
SRR065390.6144221	0	CHROMOSOME_I	999914	42	100M	*	0	0	TTCAAGCAGAGGATTTTTCGATGATTGCCAAAAATTTTGGAACTTTTATAGGCTTAAGCTTATGGTTATGTTTAGGCGTAGGCTTAGGCTTAGGCGTAGG	CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCCCCDCCCCBDCDDBBDDBDBDD@BBB@DBABDB	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:100	YT:Z:UU
SRR065390.17240207	16	CHROMOSOME_I	999901	42	100M	*	0	0	ATGTTTACAGGACTTCAAGCAGAGGATTTTTCGATGATTGCCAAAAATTTTGGAACTTTTATAGGCTTAAGCTTATGGTTATGTTTAGGCGTAGGCTTAG	CACAC?CBBAA@?@?BADDBBDBBAB>DDDBBDDABBBCCADDDDDCBCBCCCDBDDCDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:100	YT:Z:UU
```

where `samtools sort -O SAM /data/test2.sam` returns:

```
@HD	VN:1.6	SO:coordinate
@SQ	SN:CHROMOSOME_I	LN:1009800	M5:8ede36131e0dbf3417807e48f77f3ebd
@PG	ID:bowtie2	PN:bowtie2	VN:2.0.0-beta5
@PG	ID:samtools	PN:samtools	PP:bowtie2	VN:1.10-dirty	CL:./this.program sort -O SAM /data/test2.sam
SRR065390.15493040	0	CHROMOSOME_I	999912	42	100M	*	0	0	ACTTCAAGCAGAGGATTTTTCGATGATTGCCAAAAATTTTGGAACTTTTATAGGCTTAAGCTTATGGTTATGTTTAGGCGTAGGCTTAGGCTTAGGCGTA	CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDBCCBDBCCBDDA@>DC?5@?@@??:><<>8>39<37	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:100	YT:Z:UU
SRR065390.6144221	0	CHROMOSOME_I	999914	42	100M	*	0	0	TTCAAGCAGAGGATTTTTCGATGATTGCCAAAAATTTTGGAACTTTTATAGGCTTAAGCTTATGGTTATGTTTAGGCGTAGGCTTAGGCTTAGGCGTAGG	CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCCCCDCCCCBDCDDBBDDBDBDD@BBB@DBABDB	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:100	YT:Z:UU
SRR065390.17240207	16	CHROMOSOME_I	999901	42	100M	*	0	0	ATGTTTACAGGACTTCAAGCAGAGGATTTTTCGATGATTGCCAAAAATTTTGGAACTTTTATAGGCTTAAGCTTATGGTTATGTTTAGGCGTAGGCTTAG	CACAC?CBBAA@?@?BADDBBDBBAB>DDDBBDDABBBCCADDDDDCBCBCCCDBDDCDCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:100	YT:Z:UU
```

🤔

**Comment by pinbo** [comment]
I did a little research too and found it might be the pthread's problem. I compiled a wasm file for samtools by removing the pthread_create and pthread_join steps in the file bam_sort.c (function sort_blocks), then it works.
```c
        // pthread_create(&tid[i], &attr, worker, &w[i]);
        worker(&w[0]);
    }
    // for (i = 0; i < n_threads; ++i) {
    //     pthread_join(tid[i], 0);
    //     if (w[i].error != 0) {
    //         errno = w[i].error;
    //         print_error_errno("sort", "failed to create temporary file \"%s.%.4d.bam\"", prefix, w[i].index);
    //         n_failed++;
    //     }
    // }
```

**Comment by robertaboukhalil** [comment]
That's awesome, thanks @pinbo! Would you mind sending a PR for that fix in `tools/samtools/patch`? I'm also more than happy to do it. Thanks again for catching this!

**Comment by pinbo** [comment]
Hi @robertaboukhalil, I am not sure how to make a patch file. You can go ahead to do that. Thanks.

**Comment by robertaboukhalil** [comment]
FYI the fix is now live on the stg server: https://play-stg.biowasm.com/?tool=samtools, will be in prd shortly

**Comment by pinbo** [comment]
Thank you @robertaboukhalil! Really appreciate your biowasm project! Really cool and useful!

**Comment by robertaboukhalil** [comment]
You're very welcome, thanks for finding the fix! 😃
