### ISSUE TITLE
Allow shipping multiple binaries (e.g. with/without -msimd128)

### ISSUE THREAD

**Issue by milot-mirdita** [biowasm/biowasm#37]
It would be very useful to ship multiple differently compiled wasm binaries. This could be used for still being compatible with browsers that don't have WASM SIMD support, while allowing fast(er) code for browsers with WASM SIMD.

In Aioli this could I guess be done by allowing passing a function to `urlModule`, however this feature would also need biowasm cdn support.

**Comment by robertaboukhalil** [comment]
One way to do this is to have a tool's `compile.sh` output all the permutations needed. For example, for the [ssw](https://github.com/biowasm/biowasm/tree/main/tools/ssw) tool, which relies on SIMD:

* In `compile.sh`, I would also output `ssw-nosimd.wasm` by calling `emmake` without the `-msimd128` flag
* In my JS code: I can then use `Aioli("ssw/1.2.4")` for the SIMD version and `Aioli("ssw/ssw-nosimd/1.2.4")` for the version without SIMD.

**But** with this approach, it's the application that has to do feature detection and figure out which version to load, which isn't ideal--it would be useful if Aioli used [wasm-feature-detect](https://github.com/GoogleChromeLabs/wasm-feature-detect) and automatically loaded the right files for us. We might need some consistent naming scheme, and one that works when working with multiple features (e.g. for SIMD+threads, would need 4 version of the .wasm file)

**Comment by robertaboukhalil** [comment]
Done!

https://github.com/biowasm/biowasm/pull/46
https://github.com/biowasm/aioli/pull/23
