### ISSUE TITLE
[jq] quotes not accepted as in the example

### ISSUE THREAD

**Issue by Jiehong** [biowasm/biowasm#54]
Hi,

Trying to run the example in the latest version of Chrome and Firefox, an error is raised:

```
jq: error: syntax error, unexpected INVALID_CHARACTER, expecting $end (Unix shell quoting issues?) at , line 1:
'.some.data'
jq: 1 compile error
```

Removing the quotes in the jq query fixes the issue, but it means that many queries can't be passed (because they require quotes to be valid).

**Comment by robertaboukhalil** [comment]
Thanks for catching that! I updated the example on the README: https://github.com/biowasm/biowasm/tree/main/tools/jq#usage

**Comment by Jiehong** [comment]
@robertaboukhalil thanks, that's now perfect!
