### ISSUE TITLE
`latest` not loading

### ISSUE THREAD

**Issue by brwnj** [biowasm/biowasm#57]
I think it's: https://github.com/biowasm/biowasm/blob/f97d8c38989bdd98336f1427086a809d759025fc/config/tools.json#L8

In combination with 2.4.0 not being defined as a version for `base`.

**Comment by robertaboukhalil** [comment]
Thanks for pointing that out! It should be fixed now, let me know if you're still running into issues.

**Comment by brwnj** [comment]
working! thanks.
