### ISSUE TITLE
bedtools intersect -sorted in chrome vs firefox

### ISSUE THREAD

**Issue by brwnj** [biowasm/biowasm#59]
It's not behaving the same way in each browser with sorted files. firefox works whereas chrome errors out with:

```
chr13	70139383	70139429
Error: Sorted input specified, but the file a.bed has the following out of order record
chr14	92071009	92071010
```

I'm using the attached file as `-a` and https://bedqc.s3.amazonaws.com/hg38_ensembl_gene_intron.bed.gz as `-b`

```
bedtools intersect -sorted -u -a <file> -b <file>
```
[test_file.bed.gz](https://github.com/biowasm/biowasm/files/7842496/test_file.bed.gz)

**Comment by robertaboukhalil** [comment]
Hey Joe,

That's odd, I seem to get the same output in both Firefox 95 and Chrome 96, and with no errors. Which version of Chrome are you seeing this issue with?

This is the script I tried:

```html
<input id="myfile" type="file" multiple>

<script src="https://cdn.biowasm.com/v2/aioli/latest/aioli.js"></script>
<script type="module">
const CLI = await new Aioli("bedtools/2.29.2", { printInterleaved: false});
const output = await CLI.exec("bedtools --version");
console.log(`Loaded ${output.stdout}`);

async function run(event) {
    // Mount files
    const files = event.target.files;
    const paths = await CLI.mount(files);
    console.log("ls:", await CLI.ls("."), paths);

    // Run bedtools
    const output = await CLI.exec("bedtools intersect -sorted -u -a test_file.bed.gz -b hg38_ensembl_gene_intron.bed.gz");
    console.log(output.stdout);  // chr1	57367043	57367044....
    console.warn(output.stderr);  // empty
}

document.getElementById("myfile").addEventListener("change", run, false);
</script>
```

**Comment by brwnj** [comment]
Oddities in Array.sort() between Firefox and Chrome were the culprit here. Sorry to have bothered, but thought I tried everything earlier to create the same toy page. Solved on my end and thanks for your time.

https://quinlan-lab.github.io/bedqc/

**Comment by robertaboukhalil** [comment]
> https://quinlan-lab.github.io/bedqc/

Looks awesome!
