### ISSUE TITLE
Compile an existing biowasm tool

### ISSUE THREAD

**Issue by ZababurinSergei** [biowasm/biowasm#63]
Thanks for the project.

I have looked at your file.

I wanted to compile the project [CONTRIBUTING.md](https://github.com/biowasm/biowasm/blob/main/CONTRIBUTING.md)

I create file build.sh
```
# Fetch Emscripten docker image
docker pull emscripten/emsdk:2.0.25

# Create the container and mount ~/wasm to /src in the container
docker run \
    -it -d \
    -p 80:80 \
    --name wasm \
    --volume ~/wasm:/src \
    emscripten/emsdk:2.0.25

# Go into your container
docker exec -it wasm bash

# Compile seqtk
cd biowasm/
bin/compile.py --tools seqtk --versions 1.2

# This will create tools/<tool name>/build with .js/.wasm files
ls tools/seqtk/build
```
But i get error what is emcc not found.

I have little experience with docker. Can you suggest what I'm doing wrong? I did everything according to the instructions.

```
> Resetting code changes...
HEAD is now at 1a8319b r94: added "seq -S"; released 1.2
HEAD is now at 1a8319b r94: added "seq -S"; released 1.2
> Applying patch file <../patches/v1.2.patch>...
Checking patch seqtk.c...
Applied patch seqtk.c cleanly.
> Compiling...
../compile.sh: line 3: emcc: command not found
> Finalizing glue code...
ls: cannot access '../build/*.js': No such file or directory
cp tools/seqtk/build/seqtk.js /home/sergei/Desktop/system/node/biowasm/build/seqtk/1.2/
cp: cannot stat 'tools/seqtk/build/seqtk.js': No such file or directory
Return code not 0:  Command 'cp tools/seqtk/build/seqtk.js /home/sergei/Desktop/system/node/biowasm/build/seqtk/1.2/' returned non-zero exit status 1.

```

**Comment by robertaboukhalil** [comment]
Hi! In your error logs, it says `/home/sergei/Desktop/`, are you sure you're running the code inside the container?

A few things to try:

* Open a new tab on your terminal and try `docker ps`, do you see a running container called `wasm`? 
* When you enter a container using `docker exec -it wasm bash`, do you see any errors?
* If no errors, what do you see if you type `hostname`? It should be the container ID from the `docker ps` command above and not your local computer

**Comment by ZababurinSergei** [comment]
First i run this command
```
docker run -it -d  -p 80:80  --name wasm --volume ~/wasm:/src  emscripten/emsdk:2.0.25
```
Docker is runing
```
CONTAINER ID   IMAGE                     COMMAND   CREATED         STATUS         PORTS                               NAMES
097ef7694e31   emscripten/emsdk:2.0.25   "bash"    5 seconds ago   Up 4 seconds   0.0.0.0:80->80/tcp, :::80->80/tcp   wasm
```
# Go into the container
docker exec -u root -it wasm bash

I am in docker container
```
Setting environment variables:
PATH = /emsdk:/emsdk/upstream/emscripten:/emsdk/node/14.15.5_64bit/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@097ef7694e31:/src# 
```

# Compile seqtk
cd biowasm/

In container i cant see my file system
```
bash: cd: biowasm/: No such file or directory
```

... Maybe it is because my structure is wrong ?

Structure my project

```
--biowasm (clone github)
|
-build.sh

```

**Comment by robertaboukhalil** [comment]
When you're inside the container and you do `cd /src/ && ls -lah`, what do you see?

If you don't see a `biowasm` folder, then you'll need to run `git clone https://github.com/biowasm/biowasm.git`. If that fails because `git` isn't installed, I would try `apt-get install git -y` first.

**Comment by ZababurinSergei** [comment]
I was a little afraid of such an answer)

I want to keep this structure
```
/biowasm
package.json
build.sh[make, ...etc]
```

* I'm running docker. I have wasm runtime
* I'm running a script
* it goes into biosm folder
```
cd ./biowasm
```

* I get wasm module.


Clone biowasm is an extra request.

**Comment by robertaboukhalil** [comment]
> I want to keep this structure

Not sure I understand why the structure is important? If you're compiling seqtk, you need to have biowasm cloned, otherwise it won't have the info on what seqtk code to compile and how to compile it. 

> I have wasm runtime

Which Wasm runtime? Biowasm is only meant for running in the browser, so other runtimes are not supported.

> Can i get my FileSystem into docker ?

Yes, when you created your `wasm` container, there is a line that says `--volume ~/wasm:/src`, which means it mounted your local `~/wasm` path onto the docker container's `/src` path.

But that's unrelated to `wasi-fs-access` though, which is to enable a web app to access the end user's local file system

**Comment by ZababurinSergei** [comment]
I do not understand how best to transfer data from the browser to the backend and vice versa.

For example. 
I want to open the project directory in the browser and use the backend runtime.

If it were possible to pass a pointer with a mount point to the backend, it would be possible to access files in the browser on the backend.

![image](https://user-images.githubusercontent.com/108979720/215343675-1283d1a9-5c26-4436-92be-40756883b153.png)

**Comment by robertaboukhalil** [comment]
> I want to open the project directory in the browser and use the backend runtime.

You would have to pass the contents of the file to the backend server and run the tool there, but that would defeat the purpose of using WebAssembly in the browser.

To clarify, biowasm only supports running tools in the browser, not on the backend. So it doesn't support other runtimes such as Node/Wasmtime/Wasmer since it relies heavily on the browser-specific .js glue code from Emscripten

**Comment by ZababurinSergei** [comment]
From the second project, I took the terminal and connected Aioli.

I need requests to the backend to collect some modules on the side of the backend, or ask the backend to download some kind of library.

It is very convenient to manage not only the browser but the backend in this terminal.

You can send a specific backend setting from the front so that it is loaded. And send commands from the front to the console for the backend.

![image](https://user-images.githubusercontent.com/108979720/215348923-e7da1b93-bc92-4ee6-adaa-933c2df92125.png)

**Comment by robertaboukhalil** [comment]
Ah I see. I'm not too sure how to connect a backend to this, but the screenshot looks neat, good luck!
