### ISSUE TITLE
Error using gz as input file in fastp tool

### ISSUE THREAD

**Issue by atongmuuu** [biowasm/biowasm#72]
Using a gz file as an input file gets wrong, whereas unzipping to a fastq file does not.
![image](https://github.com/biowasm/biowasm/assets/62009236/33a2e578-b96c-44d6-87f8-8b312f991f10)

gz file cannot be used as input file?

**Comment by robertaboukhalil** [comment]
Hi @atongmuuu, that is strange, `fastp` **should** be able to support `.gz` files as input. The weird thing is that it works if you have paired-end `.gz` files with `--in1` and `--in2`, but it doesn't with just one. I'll have to dig deeper into this.

**Comment by robertaboukhalil** [comment]
This issue should now be fixed! 
![Screenshot 2023-08-05 at 9 56 43 PM](https://github.com/biowasm/biowasm/assets/2009870/a6306e7f-5a2b-49d5-818f-f4c84d24fbf0)
