### ISSUE TITLE
Feel free to add ViralWasm to "Who uses biowasm?"

### ISSUE THREAD

**Issue by niemasd** [biowasm/biowasm#77]
I'm working on the ViralWasm paper, and while doing so, I saw that the biowasm repo has a [Who uses biowasm?](https://github.com/biowasm/biowasm#who-uses-biowasm) section. Feel free to add [ViralWasm](https://niema-lab.github.io/ViralWasm) to the list 😄

**Comment by robertaboukhalil** [comment]
Great idea! Just updated the README and the http://biowasm.com landing page 😀
