### ISSUE TITLE
Fastp Reads Count Constraint

### ISSUE THREAD

**Issue by daniel-ji** [biowasm/biowasm#83]
I was trying to run Biowasm's fastp package on a large fastq file of 1 million sequences and it wasn't running - the CPU usage would be at around 20% on my computer and the memory would maintain ~550MB. I did the same for 600k sequences and once again it stalled at high 550MB. When I ran 500k sequences however, it worked fine, reaching the same memory usage and even going over, but still finishing. Something interesting to note is that I can select two 500k sequences and run them one after the other and it works fine (and so appending the two together simulates the behavior of running fastp on 1 million sequences). 

@robertaboukhalil followed up on this: "I traced the issue back to the variables PACK_SIZE and PACK_IN_MEM_LIMIT, which when multiplied together gives 500,000. When fastp processes >500K reads, it runs a usleep() command, which the browser can't handle. Commenting out the sleep command seems to fix the issue."

**Comment by robertaboukhalil** [comment]
@daniel-ji Should now be fixed in production. You may need to clear your cache to get the latest .wasm binary
