### ISSUE TITLE
create a pipeline

### ISSUE THREAD

**Issue by orangeSi** [biowasm/biowasm#85]
by ```Aioli```, we can run a single software at once, So it's possible to create a pipeline of multiple softwares in ```Aioli``` ? That mean  ```Aioli``` can run single software + pipeline both~

**Comment by robertaboukhalil** [comment]
Aioli doesn't support piping tools together. You can [initialize Aioli with multiple tools](https://stg.biowasm.com/documentation#aioli), but if you need a pipeline, you would not to run one tool, collect its output (usually by outputting to a file) and pass the data to the next tool

**Comment by orangeSi** [comment]
ok, if write a bash shell script to wrap multiple tools then run this shell script in Aioli  will work ?

**Comment by robertaboukhalil** [comment]
It will not, unless you compile bash to WebAssembly then execute the shell script, which would be a very large effort
